replicaCount: 1

image:
  repository: dockertech28/my-app
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount: 
  create: false
  name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  # nodePort: 30080

# service:
#   type: NodePort
#   port: 80
#   targetPort: 3000
#   nodePort: 30007

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

env:
  LOG_LEVEL: info

ingress:
  enabled: true
hpa:
  enabled: false
httpRoute:
  enabled: false
