name: Helm Deployment (KIND)

on:
  workflow_call:
    inputs:
      deployment-repo:
        required: true
        type: string
      app:
        required: true
        type: string
      env:
        required: true
        type: string
      region:
        required: true
        type: string
      latest-chart:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout deployment repo
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.deployment-repo}}
          token: ${{ secrets.GH_PAT }}
          path: deployment-repo

      # Install Docker (already available in runner)

      # Install kind
      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Create kind cluster
      - name: Create KIND cluster
        run: |
          kind create cluster --name cicd-cluster

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # Verify cluster
      - name: Verify Cluster
        run: kubectl get nodes

      # Deploy using Helm
      - name: Deploy using Helm
        run: |
          cd deployment-repo
          helm upgrade --install ${{ inputs.app }} ./apps/${{ inputs.app }}/helm-chart/ \
            --namespace ${{ inputs.env }} \
            --create-namespace \
            -f ./apps/${{ inputs.app }}/${{ inputs.app }}.yaml \
            -f ./environments/${{ inputs.env }}/${{ inputs.app }}.yaml
